//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge2_v2.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnersOnly
    {
        public int OwnerID { get; set; }
        public string Surname { get; set; }
        public string GivenName { get; set; }
        public string Phone { get; set; }
    }
}
