//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge2_v2.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentsOnly
    {
        public int TreatmentID { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public decimal Price { get; set; }
        public int PetID { get; set; }
        public int ProcedureID { get; set; }
    }
}
